---
abstract: 'Perl extension for using an embedding WebKit engine for Catalyst tests'
author:
  - 'Stefan Seifert <nine@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-WebKit-Catalyst
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst::EngineLoader: 0
  IO::Socket::INET: 0
  Test::More: 0
  Test::WWW::WebKit: 0.01
version: 0.01
